import Image from "next/image";
import Link from "next/link";
import Reveal from "./reveal";
export default function Home() { return <>
  <Reveal><section className="hero"><Image className="hero-image" src="https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=2400&q=85" alt="People gathered around a table in conversation" fill priority unoptimized sizes="100vw" /><div className="wrap hero-content"><div className="hero-copy-block"><p className="eyebrow">People at the core. Purpose in the work.</p><h1>Matthew<br />Olszewski</h1><p className="hero-copy">Building toward a more human<br />side of technology.</p><div className="actions"><Link className="button" href="/projects">Explore my work &rarr;</Link><Link className="text-link" href="/about">Start with my why &rarr;</Link></div></div><div className="hero-portrait"><Image src="/matthew-headshot.jpg" alt="Portrait of Matthew Olszewski" fill priority sizes="(max-width: 700px) 180px, (max-width: 1000px) 260px, 390px" /></div></div><div className="wrap hero-caption"><span>Computer Science &amp; Engineering</span><span>The Ohio State University</span></div></section></Reveal>
  <Reveal><section className="wrap section intro"><p className="eyebrow">01 / A little about me</p><div><h2>Good solutions<br />start with people.</h2><p className="lead">I&apos;m a senior in Computer Science and Engineering at Ohio State, with minors in Business and Mathematics. My focus is simple: keep people at the center of what I build.</p><Link className="text-link" href="/about">The purpose behind the work &rarr;</Link></div></section></Reveal>
  <Reveal><section className="band"><div className="wrap section"><div className="section-heading"><div><p className="eyebrow">02 / Currently building</p><h2>A place to connect.</h2></div><Link className="text-link" href="/projects">Explore projects &rarr;</Link></div><Link href="/projects" className="project"><div className="project-art" aria-hidden="true"><strong>MNO.</strong><span>People. Purpose. Possibility.</span></div><div><p className="eyebrow">Personal website / In progress</p><h3>A home for my story.</h3><p className="description">Bringing my work, education, and perspective together in one place.</p><span className="text-link">View the project &rarr;</span></div></Link></div></section></Reveal>
  <Reveal><section className="wrap section"><p className="eyebrow">03 / Make a connection</p><h2>It starts with<br />a conversation.</h2><Link className="button spaced" href="/connect">Connect with me &rarr;</Link></section></Reveal>
  </>; }
